version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=budget_control
      - DB_USER=budget_user
      - DB_PASSWORD=budget_password
      - APP_ENV=development
    volumes:
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - db
    networks:
      - budget-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=budget_control
      - MYSQL_USER=budget_user
      - MYSQL_PASSWORD=budget_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema_mysql.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - budget-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=budget_user
      - PMA_PASSWORD=budget_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - budget-network

volumes:
  db_data:

networks:
  budget-network:
    driver: bridge