services:
  - type: web
    name: budget-control-php
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      mkdir -p public/uploads
      chmod 755 public/uploads
    startCommand: |
      php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: PHP_VERSION
        value: "8.1"
      - key: DB_HOST
        fromDatabase:
          name: budget-control-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: budget-control-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: budget-control-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: budget-control-db
          property: password
      - key: DB_PORT
        value: "3306"
      - key: APP_ENV
        value: "production"

databases:
  - name: budget-control-db
    databaseName: budget_control
    user: budget_user