<?php 
 /** 
  * Database Configuration 
  * Generated by Installation Wizard 
  */ 
 
 class Database { 
    private $host = 'localhost'; 
    private $port = 3306; 
    private $db_name = 'subyaisite_budget'; 
    private $username = 'root'; 
    private $password = ''; 
     public $conn; 
 
     public function getConnection() { 
         $this->conn = null; 
         try { 
             $this->conn = new PDO( 
                 "mysql:host=" . $this->host . ";port=" . $this->port . ";dbname=" . $this->db_name . ";charset=utf8mb4", 
                 $this->username, 
                 $this->password, 
                 [ 
                     PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, 
                     PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4" 
                 ] 
             ); 
         } catch(PDOException $exception) { 
             error_log("Connection error: " . $exception->getMessage()); 
             throw $exception; 
         } 
         return $this->conn; 
     } 
 } 
 ?>